# Generated by Django 2.0.5 on 2020-05-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('pcost', models.IntegerField()),
                ('pcolor', models.CharField(max_length=50)),
                ('pclass', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('cmobile', models.BigIntegerField()),
                ('cemail', models.EmailField(max_length=50)),
            ],
        ),
    ]
